spring:
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: "true"
      properties:
         hibernate:
            dialect: "org.hibernate.dialect.MySQL5Dialect"
   database:
      dirverClassName: "com.mysql.jdbc.Driver"
   datasource:
      url: "jdbc:mysql://localhost:3306/spring_batch"
      username: "username"
      password: "{cipher}a29e1cd6731cccbafde37bcfb947006aea482091aca57862f25a0b53c3e24e4e"
      testWhileIdle: "true"
      validationQuery: "SELECT 1"    
      
security:
   basic:
      enabled: false   
      
      
server:
   port: 8082            
                                